version: 0.2
env:
  variables:
    DOCKER_HUB_USERNAME: "akshaykomath1"
    DOCKER_HUB_PASSWORD: "Achu@kalady15"
phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $DOCKER_HUB_USERNAME/nodejs-webapp:latest .
      - docker tag $DOCKER_HUB_USERNAME/nodejs-webapp:latest $DOCKER_HUB_USERNAME/nodejs-webapp:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to Docker Hub...
      - docker push $DOCKER_HUB_USERNAME/nodejs-webapp:latest
      - docker push $DOCKER_HUB_USERNAME/nodejs-webapp:$IMAGE_TAG
