version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14  # Use the Node.js Docker image
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Success Message
          command: echo "Pipeline ran successfully!"

  # Optionally, you can add a deploy job if needed
  # deploy:
  #   docker:
  #     - image: circleci/node:14
  #   steps:
  #     - checkout
  #     - run:
  #         name: Docker Build
  #         command: docker build -t your-dockerhub-
