version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14  # Use the Node.js image
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build Application
          command: npm run build
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Docker Build
          command: docker build -t akshaykomath1/your-image-name:$CIRCLE_SHA1 .
      - run:
          name: Docker Push
          command: |
            echo "akshaykomath1" | docker login -u "akshaykomath1" --password-stdin
            docker push akshaykomath1/your-image-name:$CIRCLE_SHA1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
